services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/appuser/app/src
      - ./alembic:/home/appuser/app/alembic
      - uploads_data:/home/appuser/app/uploads
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
      worker:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@db:5432/cogni_graph_db

  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cogni_graph_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cogni_graph_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc"]
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  worker:
    build: .
    command: celery -A src.celery_worker.celery_app worker --loglevel=info
    volumes:
      - ./src:/home/appuser/app/src
      - uploads_data:/home/appuser/app/uploads
    depends_on:
      redis:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "celery", "-A", "src.celery_worker.celery_app", "inspect", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  neo4j_data:
  uploads_data: