services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/appuser/app/src
      - ./alembic:/home/appuser/app/alembic
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/cogni_graph_db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cogni_graph_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cogni_graph_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: