services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/appuser/app/src
      - ./alembic:/home/appuser/app/alembic
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg://user:password@db:5432/cogni_graph_db

  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cogni_graph_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d cogni_graph_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  neo4j_data: