apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: 215288576473.dkr.ecr.ap-southeast-1.amazonaws.com/cogni-graph-api
    newTag: ${{ github.sha }}