apiVersion: apps/v1
kind: Deployment
metadata:
  name: cogni-graph-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: 215288576473.dkr.ecr.ap-southeast-1.amazonaws.com/cogni-graph-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
          ports:
            - containerPort: 8000
          env:
            - name: NEO4J_URI
              valueFrom:
                configMapKeyRef:
                  name: cogni-graph-config
                  key: NEO4J_URI
            - name: NEO4J_USER
              valueFrom:
                configMapKeyRef:
                  name: cogni-graph-config
                  key: NEO4J_USER
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-credentials
                  key: password
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cogni-graph-secrets
                  key: OPENAI_API_KEY
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: cogni-graph-config
                  key: REDIS_HOST
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cogni-graph-config
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              value: "cogni_graph_db"
            - name: DB_USER
              value: "cogni_user"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cogni-graph-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: 215288576473.dkr.ecr.ap-southeast-1.amazonaws.com/cogni-graph-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - "celery -A src.celery_worker.celery_app worker --loglevel=info"
          env:
            - name: NEO4J_URI
              valueFrom:
                configMapKeyRef:
                  name: cogni-graph-config
                  key: NEO4J_URI
            - name: NEO4J_USER
              valueFrom:
                configMapKeyRef:
                  name: cogni-graph-config
                  key: NEO4J_USER
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-credentials
                  key: password
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cogni-graph-secrets
                  key: OPENAI_API_KEY
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: cogni-graph-config
                  key: REDIS_HOST
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: cogni-graph-config
                  key: DB_HOST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: DB_NAME
              value: "cogni_graph_db"
            - name: DB_USER
              value: "cogni_user"